!include Style.puml
@startuml
title After Command "short qn4/ans4/module/difficulty"

object ":QuestionList" as QuestionList

object ":Question1" as Question1

object ":Question2" as Question2

object ":Question3" as Question3

object ":Question4" as Question4

QuestionList -->  Question1
QuestionList --> Question2
QuestionList --> Question3
QuestionList --> Question4 : Add new question
@enduml
