@startuml
!theme plain
hide footbox
title Command Edit Sequence Diagram

actor User
participant QuizHub as ":QuizHub"
participant Parser as ":Parser"
participant CommandEdit as "c:CommandEdit"
participant QuestionList as ":QuestionList"
participant Question as ":Question"
participant MCQOption as ":MCQOption"

User -> QuizHub: Enters "edit [question number] /description [description], /answer [answer], or /option[1...4] [newAnswer]"
activate QuizHub
QuizHub -> Parser : parseCommand(userInput)
activate Parser
create CommandEdit
Parser -> CommandEdit: Calls parseEditCommand(userInput)

activate CommandEdit
CommandEdit --> Parser
deactivate CommandEdit
Parser --> QuizHub : c
deactivate Parser
QuizHub -> CommandEdit: Executes executeCommand(ui, dataStorage, questions)
activate CommandEdit
alt if editing description or answer
    CommandEdit -> QuestionList: Calls editQuestionByIndex(index, newDescription, newAnswer)
    activate QuestionList
    QuestionList -> Question: Calls editQuestion(newDescription, newAnswer)
    activate Question
    Question -> Question: Edits question description and/or answer
    Question --> QuestionList: Notifies edit completion
    deactivate Question
    QuestionList --> CommandEdit: Notifies edit completion
    deactivate QuestionList
else if editing MCQ option
    CommandEdit -> QuestionList: Calls editMCQOptionByIndex(index, optionNumber, newOption)
    activate QuestionList
    QuestionList -> MCQOption: Calls editOption(optionNumber, newOption)
    activate MCQOption
    MCQOption -> MCQOption: Updates the specified option
    MCQOption --> QuestionList: Notifies option edit completion
    deactivate MCQOption
    QuestionList --> CommandEdit: Notifies option edit completion
    deactivate QuestionList
end
CommandEdit --> QuizHub: Notifies edit completion
deactivate CommandEdit
QuizHub --> User: Displays edit completion message
destroy CommandEdit

@enduml
