@startuml
'https://plantuml.com/sequence-diagram

autonumber

Main -> EditPriceCommand: execute()
activate EditPriceCommand
EditPriceCommand -> Dish: setPrice(price: float)
activate Dish
EditPriceCommand -> Ui: showEditPriceMessages()
deactivate EditPriceCommand
deactivate Dish
@enduml
