@startuml
hide footbox
actor User
participant ":CheckOutCommand" as CheckOutCommand
participant ":Cart" as Cart
participant ":StockEntry" as StockEntry
participant ":Drug" as Drug
participant ":CartEntry" as CartEntry
participant ":SalesList" as SalesList
participant ":CommandResult" as CommandResult

User -> CheckOutCommand: execute()
activate User
activate CheckOutCommand

alt Cart is not empty
  CheckOutCommand -> Cart: getCurrentCart()
  activate Cart
  Cart -> Cart: Retrieve current cart
  Cart -> Cart: Create temporary holder (List<CartEntry>)
  Cart -> StockEntry: Get StockEntry for each entry
  activate StockEntry
  loop over entries
    activate Drug
    StockEntry -> Drug: Get Drug
    activate Drug
    Drug -> Drug: Get SellingPrice
    Drug --> StockEntry
    StockEntry --> CartEntry: Create CartEntry with quantity and selling price
    deactivate Drug
    deactivate StockEntry
    deactivate CartEntry
  end
  Cart -> SalesList: Add temporary holder to sold items
  Cart -> CommandResult: Create result message
  deactivate Cart
  Cart --> User: Message with total cost
  else
  Cart -> CommandResult: Cart is empty
  Cart --> User: Message failure
end

User --> CheckOutCommand: CommandResult
deactivate User
deactivate CheckOutCommand
@enduml
