@startuml
hide footbox
actor User
participant ListSalesCommand
participant SalesList
participant CommandResult

User -> ListSalesCommand: execute()
activate User
activate ListSalesCommand

alt SalesList is not empty
  ListSalesCommand -> SalesList: Get sales data
  activate SalesList
  SalesList --> ListSalesCommand: List of sales
  deactivate SalesList
  ListSalesCommand --> CommandResult: List of sales
  else
  ListSalesCommand --> CommandResult: SalesList is empty
end

User --> ListSalesCommand: CommandResult
deactivate User
deactivate ListSalesCommand
@enduml
