@startuml
hide footbox
actor User
participant "User Input" as UserInput
participant ": Parser" as Parser
participant ": Command" as Command
participant ": CommandResult" as CommandResult


User -> UserInput: Enter command
UserInput -> Parser: parseCommand(userInput)
activate Parser
Parser -> Command: execute(model)
deactivate Parser
activate Command
Create CommandResult
Command -> CommandResult
activate CommandResult
CommandResult --> Command
deactivate CommandResult
Command --> User




@enduml
