@startuml

participant ":VisCommand"
participant "<<class>>\nUi"
participant "<<class>>\nCashFlowList"
participant "<<class>>\nCategorizer"
participant "<<class>>\nVisualizer"

":VisCommand"-> "<<class>>\nUi": getInstance()

":VisCommand"-> "<<class>>\nCashFlowList": getInstance()

":VisCommand"-> "<<class>>\nUi": printDisplayChart(type)

ref over "<<class>>\nCategorizer", ":VisCommand" : sort cashflow entries

ref over "<<class>>\nVisualizer", ":VisCommand": displaying chart

hide footbox

@enduml