@startuml

participant ":VisCommand"
participant ":Ui"
participant "<<class>>\nCategorizer"
participant "<<class>>\nVisualizer"

":VisCommand"-> ":Ui": printDisplayChart(type)

ref over "<<class>>\nCategorizer", ":VisCommand" : sort cashflow entries

alt #Pink cashflowbyType.empty()

    ":VisCommand" -> ":Ui" : ui.printEmptyCashflow(type)

else #LightBlue !cashflowbyType.empty()

    ref over "<<class>>\nVisualizer", ":VisCommand": displaying chart

end


hide footbox

@enduml