@startuml

mainframe sd displaying chart

participant ":VisCommand"
participant "<<class>>\nVisualizer"

activate ":VisCommand"
":VisCommand"-> "<<class>>\nVisualizer": displayChart(chart, sortedCashFlow, type)

activate "<<class>>\nVisualizer"
alt "pie"
    "<<class>>\nVisualizer" -> "<<class>>\nVisualizer": displayPieChart(cashflowList, type)
    activate "<<class>>\nVisualizer"
    return
else "bar"
    "<<class>>\nVisualizer" -> "<<class>>\nVisualizer": displayBarChart(cashflowList, type)
    activate "<<class>>\nVisualizer"
    return
else "radar"
    "<<class>>\nVisualizer" -> "<<class>>\nVisualizer": displayRadarChart(cashflowList, type)
    activate "<<class>>\nVisualizer"
    return
end
return


hide footbox

@enduml