@startuml
!include Style.puml
title Command Edit Sequence Diagram

actor User
participant QuizHub as ":QuizHub"
participant Parser as ":Parser"
participant CommandEdit as "c:CommandEdit"
participant QuestionList as ":QuestionList"
participant Question as ":Question"

User -> QuizHub: Enters "edit [question number] /description [description] or /answer [answer]"
activate QuizHub
QuizHub -> Parser : parseCommand(userInput)
activate Parser
create CommandEdit
Parser -> CommandEdit: Calls parseEditCommand(userInput)

activate CommandEdit
CommandEdit --> Parser
deactivate CommandEdit
Parser --> QuizHub : c
deactivate Parser
QuizHub -> CommandEdit: Executes executeCommand(ui, dataStorage, questions)
activate CommandEdit
CommandEdit -> QuestionList: Calls editQuestionByIndex(index, editField, newValue)
activate QuestionList
QuestionList -> Question: Calls editQuestion(editField, newValue)
activate Question
Question -> Question: Edits question description and/or answer
Question --> QuestionList: Notifies edit completion
deactivate Question
QuestionList --> CommandEdit: Notifies edit completion
deactivate QuestionList
CommandEdit --> QuizHub: Notifies edit completion
deactivate CommandEdit
QuizHub --> User: Displays edit completion message
destroy CommandEdit

@enduml
