@startuml
!include Style.puml
left to right direction
rectangle Ui
rectangle QuizHub
rectangle Storage
rectangle Commands
rectangle Parser
rectangle UtilityClasses

Ui --> Parser
QuizHub <-[dotted]-> Storage
Commands --> QuizHub
Parser --> Commands
QuizHub --> Ui

@enduml