@startuml

participant ":AddCashflowCommand" as AddCashflowCommand
participant "CashflowList" as CashflowList
participant ":Income" as Income
participant ":Expense" as Expense
participant "Ui" as Ui

-> AddCashflowCommand: execute()
alt income
    AddCashflowCommand -> CashflowList: addIncome(amount, incomeType, recur, description)
    create Income
    CashflowList -> Income: Income(value, type, recur, description)
    Income -> Income: addIncomeValue()
    CashflowList -> CashflowList: addToList(toAdd)
    CashflowList -> Ui: printAddedCashflow(toAdd)

else expense
    AddCashflowCommand -> CashflowList: addExpense(amount, incomeType, recur, description)
    create Expense
    CashflowList -> Expense: Expense(value, type, recur, description)
    Expense -> Expense: addExpenseValue()
    CashflowList -> CashflowList: addToList(toAdd)
    CashflowList -> Ui: printAddedCashflow(toAdd)
else invalid command
end

hide footbox
@enduml