@startuml

participant ":AddCashflowCommand" as AddCashflowCommand
participant "<<class>>\nCashflowList" as CashflowList
participant ":Income" as Income
participant ":Expense" as Expense
participant "<<class>>\nUi" as Ui

-> AddCashflowCommand: execute()
AddCashflowCommand -> CashflowList: getInstance()
CashflowList -> Ui: getInstance()
alt income
    AddCashflowCommand -> CashflowList: addIncome(amount, incomeType, recur)
    create Income
    CashflowList -> Income: Income(value, type, recur)
    Income -> Income: addIncomeValue()
    CashflowList -> CashflowList: add(toAdd)
    CashflowList -> Ui: printAddedCashflow(toAdd)

else expense
    AddCashflowCommand -> CashflowList: addExpense(amount, incomeType, recur)
    create Expense
    CashflowList -> Expense: Expense(value, type, recur)
    Expense -> Expense: addExpenseValue()
    CashflowList -> CashflowList: add(toAdd)
    CashflowList -> Ui: printAddedCashflow(toAdd)
else invalid command
end

hide footbox
@enduml