@startuml
!include style.puml
skinparam ArrowFontStyle plain

participant ":AddIngredientCommand" as AddIngredientCommand COMMAND_COLOR
participant "<<class>>\nIngredientParser" as IngredientParser LOGIC_COLOR
participant ":Ingredient" as Ingredient LOGIC_COLOR
participant "ingredients:IngredientList" as Ingredients LOGIC_COLOR
participant "<<class>>\nUi" as Ui INTERFACE_COLOR


[-> AddIngredientCommand : executeCommand()
activate AddIngredientCommand

loop //all ingredients//
    AddIngredientCommand -> IngredientParser : parseIngredient(ingredients, newIngredientDetails)
    activate IngredientParser

    IngredientParser -> IngredientParser : mapIngredientUnit(ingredientUnitValue)

    create Ingredient
    IngredientParser -> Ingredient : Ingredient(ingredientName, ingredientQuantity, ingredientUnit)
    activate Ingredient

    Ingredient -> IngredientParser : newIngredient
    deactivate Ingredient

    IngredientParser --> AddIngredientCommand : newIngredient

deactivate IngredientParser

AddIngredientCommand -[hidden]> IngredientParser

AddIngredientCommand -[hidden]> Ingredient


AddIngredientCommand -[hidden]> Ingredients
AddIngredientCommand -> Ingredients : addIngredient(newIngredient)
activate Ingredients

Ingredients -> Ingredients: ingredients.add(newIngredient)
activate Ingredients RECIPE_LIST_COLOR_T1
deactivate Ingredients

Ingredients --> AddIngredientCommand
deactivate Ingredients

AddIngredientCommand -[hidden]> Ui
AddIngredientCommand -> Ui : printAddIngredientsSuccess(ingredientName)
activate Ui

Ui -> Ui: print ingredient added success message
activate Ui INTERFACE_COLOR_T1

Ui -> Ui: print divider
deactivate Ui INTERFACE_COLOR_T1

Ui --> AddIngredientCommand
deactivate Ui
end

[<--AddIngredientCommand
deactivate AddIngredientCommand
@enduml