@startuml

autoactivate on

participant ":BudgetCommand" as BudgetCommand
participant "<<class>>\nBudget" as Budget
participant ":Ui" as Ui

-> BudgetCommand: execute()

alt set
    BudgetCommand -> Budget: setBudget(budget)
    return
    BudgetCommand -> Ui: printSetBudget()
    return
else update
    BudgetCommand -> Ui: printBudgetBeforeUpdate()
    return
    BudgetCommand -> Budget: updateBudget(budget)
    return
    BudgetCommand -> Ui: printBudgetAfterUpdate()
    return
else delete
    ref over BudgetCommand: DeleteBudget
else reset
    ref over BudgetCommand: ResetBudget
else view
    ref over BudgetCommand: ViewBudget
else invalid command
end

return

hide footbox
@enduml