@startuml

participant ":BudgetCommand" as BudgetCommand
participant "<<class>>\nBudget" as Budget
participant "<<class>>\nUi" as UiClass
participant ":Ui" as Ui

-> BudgetCommand: execute()
BudgetCommand -> UiClass: getInstance()

alt set
    BudgetCommand -> Budget: setBudget(budget)
    BudgetCommand -> Ui: printSetBudget()
else update
    BudgetCommand -> Ui: printBudgetBeforeUpdate()
    BudgetCommand -> Budget: updateBudget(budget)
    BudgetCommand -> Ui: printBudgetAfterUpdate()
else delete
    ref over BudgetCommand: DeleteBudget
else reset
    ref over BudgetCommand: ResetBudget
else view
    ref over BudgetCommand: ViewBudget
else invalid command
end

hide footbox
@enduml