@startuml
!include style.puml
skinparam ArrowFontStyle plain

actor User
participant ":EssenMakanan" as EssenMakanan MAIN_COLOR
participant ":Parser" as Parser PARSER_COLOR
participant "command:CheckRecipeCommand" as Command COMMAND_COLOR
participant "<<class>>\n:RecipeParser" as RecipeParser RECIPE_PARSER_COLOR
participant "<<class>>\nUi" as Ui INTERFACE_COLOR
participant "ingredients:IngredientList" as Ingredients INGREDIENT_COLOR

User -> EssenMakanan: input: start curry chicken
activate EssenMakanan

EssenMakanan -> Parser : parseCommand()
activate Parser

create Command
Parser -> Command: Command()
activate Command

Command --> Parser : command

Parser -> EssenMakanan: command
deactivate Parser

EssenMakanan -> Command: executeCommand()

Command -> RecipeParser : getRecipeIndex()
activate RecipeParser

RecipeParser --> Command
deactivate RecipeParser


Command -> Command : getmissingIngredients()
activate Command

Command --> Command : missing ingredients
deactivate Command


Command -> Ui: printStartRecipeMessage()
activate Ui

Ui -> Ingredients: listIngredients()
activate Ingredients

Ingredients --> Ui
deactivate Ingredients

Ui --> Command

deactivate Ui

Command --> EssenMakanan
deactivate Command

deactivate EssenMakanan

@enduml