@startuml

mainframe sd DeleteBudget
participant BudgetCommand
participant Budget
participant Ui

alt hasBudget
    BudgetCommand -> Budget: deleteBudget()
    BudgetCommand -> Ui: printDeleteBudget()
else else
    BudgetCommand -> Ui: printBudgetError("delete")
end

hide footbox
@enduml