@startuml
!include style.puml
skinparam ArrowFontStyle plain

actor User

participant ":EssenMakanan" as EssenMakanan MAIN_COLOR
participant ":Parser" as Parser PARSER_COLOR
participant "command:HelpCommand" as HelpCommand COMMAND_COLOR
participant "<<class>>\nUi" as Ui INTERFACE_COLOR

User-> EssenMakanan : input: help
activate EssenMakanan

EssenMakanan -> Parser : parseCommand("help", recipes, ingredients)
activate Parser

create HelpCommand
Parser -> HelpCommand
activate HelpCommand


HelpCommand --> Parser : command

Parser --> EssenMakanan: command
deactivate Parser

EssenMakanan -> HelpCommand : executeCommand()

HelpCommand -> Ui : showCommands()
activate Ui

Ui --> HelpCommand
deactivate Ui

HelpCommand --> EssenMakanan
deactivate HelpCommand

deactivate EssenMakanan

@enduml