@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor CLASS_ARROW_COLOR
skinparam classBackgroundColor CLASS_DIAGRAM_COLOR

Class IngredientList {
    - ingredients: Ingredient[]
    + getIngredients: Ingredient[]
    + getIngredient: Integer
}


Class Ingredient

Class "<<enumeration>>\nIngredientUnit" as IngredientUnit

IngredientList -down-> "*" Ingredient

Ingredient "*" *-down-> "1" IngredientUnit
@enduml
