@startuml
!include style.puml
skinparam arrowThickness 1.1
skinparam arrowColor CLASS_ARROW_COLOR
skinparam classBackgroundColor CLASS_DIAGRAM_COLOR

Class RecipeList
Class Recipe
Class RecipeIngredientList
Class "<<enumeration>>\nTag" as Tag
Class RecipeStepList
Class Ingredient
Class Step

RecipeList -down-> "*" Recipe

Recipe -down-> "1" RecipeIngredientList
Recipe *-down-> "0...4" Tag
Recipe -down-> "1" RecipeStepList

RecipeIngredientList -down-> "1...*" Ingredient
RecipeStepList -down-> "1...*" Step
@enduml
