@startuml

mainframe sd ResetBudget
participant BudgetCommand
participant Budget
participant Ui

alt spentBudget
    opt initialBudgetExceedBalance
        BudgetCommand -> Budget: setInitialBudget(balance);
        BudgetCommand -> Ui: printUpdateMessage()
    end
    BudgetCommand -> Budget: resetBudget()
    BudgetCommand -> Ui: printResetBudget()
else else
    BudgetCommand -> Ui: printErrorMessage()
end

hide footbox
@enduml