@startuml
'https://plantuml.com/class-diagram
!include style.puml
skinparam ClassBackgroundColor STORAGE_COLOR

package Storage as StoragePackage {
Class Storage
Class "{abstract}\nLoadData" as LoadData
Class "{abstract}\nSaveData" as SaveData
Class CashflowList
Class Budget
Class Cashflow
Class Expense
Class Income
Class "<<enumeration>>\nExpenseType" as ExpenseType
Class "<<enumeration>>\nIncomeType" as IncomeType
Class Ui
}

Class FinancialPlanner #FFFFFF
FinancialPlanner --> Storage

Storage .right.-> LoadData: uses >
Storage .left.> SaveData: uses >
SaveData ..> CashflowList
SaveData ..> Budget
LoadData ..> CashflowList
LoadData ..> Budget
LoadData ..> ExpenseType
LoadData ..> IncomeType
SaveData ..> Expense
SaveData ..> Income
LoadData ..> Expense
LoadData ..> Income
LoadData -right-> Ui: prints message >
Expense -down-|> Cashflow
Income -down-|> Cashflow

@enduml