@startuml
!define COMMAND class ListIngredientCommand
!define UI class Ui
!define MAIN class Main
!define STORAGE class Storage
!define DATA class Data
!define PARSER class Parser
!define COMMAND class Command

autonumber
Actor user

Main -> Storage : load()
Activate Main
Activate Storage
Storage -> Storage : decode()

Activate Storage
Storage -> Data
Activate Data
Data-> Storage : ArrayList
Deactivate Data
Return
Storage -> Main : menu: Menu

user->Ui





@enduml
