@startuml
!define COMMAND class ":ListIngredientCommand"
!define UI class ":Ui"
!define MENU class ":Menu"
!define DISH class ":Dish"
!define PARSER class Parser

autonumber

 -> ":ListIngredientCommand": execute()

activate ":ListIngredientCommand"
":ListIngredientCommand" -> ":Menu" : getMenuItemsList()
activate ":Menu"
":Menu" --> ":ListIngredientCommand": selectedDish : ":Dish"
deactivate ":Menu"

":ListIngredientCommand" -> ":Ui" : showListIngredientsMessage(selectedDish: Dish)
activate ":Ui"

":Ui" -> ":Ui" : showDishName(dish: Dish)
activate ":Ui"
":Ui" -> ":Dish" : dish.getName()
activate ":Dish"
return : String
return

":Ui" -> ":Ui" : showIngredientList(dish : Dish)
activate ":Ui"

":Ui" -> ":Dish" : selectedDish.getIngredients()
activate ":Dish"
return ingredients: ArrayList<Ingredient>



loop ingredients
":Ui" -> ":Ingredients": ingredient.getName()
activate ":Ingredients"
":Ingredients" --> ":Ui" :String
deactivate ":Ingredients"
":Ui" -> ":Ingredients": ingredient.getQty()
activate ":Ingredients"
":Ingredients" --> ":Ui" :int
deactivate ":Ingredients"
":Ui" -> ":Ingredients": ingredient.getUnit()
activate ":Ingredients"
":Ingredients" --> ":Ui" :String
deactivate ":Ingredients"
":Ui" -> ":Ui" : formatListIngredient(ingredientName: String, ingredientAmount: String)
activate ":Ui"
return
end loop

":Ui" -> ":Ui": showIngredientsEndCap()
activate ":Ui"
return
return
return

@enduml