@startuml

skinparam Style strictuml

activate ViewBudget
ViewBudget -> BudgetHandler: printBudget()
activate BudgetHandler

BudgetHandler -> BudgetHandler: setBudgetPercentage()
activate BudgetHandler
BudgetHandler -> FinancialStatement: getNetCash()
activate FinancialStatement
FinancialStatement --> BudgetHandler

BudgetHandler -> Progress: Progress(cashOnHand, budgetAmount)
activate Progress
Progress --> BudgetHandler
BudgetHandler --> BudgetHandler
deactivate BudgetHandler


alt budget.isActive()

    opt budgetHasBeenMaxedOut
        BudgetHandler -> BudgetHandler: printSeriousWarning()
        activate BudgetHandler
        BudgetHandler --> BudgetHandler
        deactivate BudgetHandler

    else budgetIsNotOnTrack
        BudgetHandler -> BudgetHandler: printBasicWarning()
        activate BudgetHandler
        BudgetHandler --> BudgetHandler
        deactivate BudgetHandler
    end


    BudgetHandler -> Ui: printMultipleText(texts)
    activate Ui

    Ui -> Budget: toString()
    activate Budget
    Budget --> Ui
    deactivate Budget

    Ui -> FinancialStatement: getNetCash()

    FinancialStatement --> Ui
    deactivate FinancialStatement
    Ui -> Progress: displayProgressBar()
    Progress --> Ui
    Ui --> BudgetHandler
    deactivate Ui

else
    <--BudgetHandler: throw CashLehBudgetException(text)

end
BudgetHandler --> ViewBudget
deactivate ViewBudget
deactivate BudgetHandler

@enduml