@startuml
!define COMMAND class ListIngredientCommand
!define UI class Ui
!define MENU class Menu

autonumber

Main -> Parser: parseCommand()
activate Parser
Parser -> Parser: prepareDelete()
activate Parser
return DeleteDishCommand()
return DeleteDishCommand()

Main -> DeleteDishCommand: execute()
activate DeleteDishCommand
DeleteDishCommand -> Menu: getMenuItemsList()
activate Menu
return (selectedDish: Dish)

DeleteDishCommand -> Ui: showDeleteMessage()
activate Ui
Ui -> Ui: showToUser()
activate Ui
return
return
DeleteDishCommand -> Menu: removeDish()
activate Menu
return

@enduml