@startuml
'https://plantuml.com/sequence-diagram

":CashLeh" -> ":Input": getInputString()
activate ":Input"
":Input" --> ":CashLeh": inputString
deactivate ":Input"

":CashLeh" -> ":Parser": parse(inputString)
activate ":Parser"

create ":Command"
":Parser" -> ":Command": command
activate ":Command"
":Command" -> ":Command": execute()
activate ":Command"
":Command" --> ":Command"
deactivate ":Command"
":Command" --> ":Parser"
deactivate ":Command"
":Parser" --> ":CashLeh"

deactivate ":Parser"


@enduml