@startuml
'https://plantuml.com/sequence-diagram

actor User

User -> Main: fullUserInput
activate Main
Main -> Parser: parseCommand(fullUserInput: String)
activate Parser

alt COMMAND_WORD
Parser -> Parser: prepareCommand(requiredArguments)
activate Parser
Parser -> Command: Command()
activate Command
Command --> Parser: command
deactivate Command
deactivate Parser
end alt

deactivate Parser

Parser --> Main: command
Main -> Command: execute()
activate Command
@enduml
